### ISSUE TITLE
Textual Inversions no longer usable after I installed Card Master

### ISSUE THREAD

**Issue by MxProteus** [SenshiSentou/sd-webui-cardmaster#10]
Updated everything today for the first time in awhile, once everything reloaded I got the message about Card Master replacing tiny card, So I did as it said. Everything seemed to be fine, got all my stuff set ready to run some generations, went into my TI's  clicked on one I wanted to use and I got nothing. 

My TI's are all still there but I can no longer just click on them and they populate the prompt. Not sure what to do with that situation so I  restored my backup before the update so all my stuff worked again, didn't get a chance to check Hypernetworks, kind of forgot about them since I only have two that I rarely use, so not sure if the problems are there as well.

Also noticed when using it on the LoRa's it put an apostrophe between the "<LoRa>, activation word" don't know if it makes a difference or not because I never did a generation with it. I'll read the instructions here because I couldn't figure out the green light red light plus and minus stuff, not sure what purpose it serves.

**Comment by MxProteus** [comment]
Ok, I enabled Cardmaster again because when I reverted to the backup a different tool no longer worked, So I'm stuck with cardmaster and not being able to use my TI's or my Hypernetworks.

That being said, I have 3 TI's that do work but their not working properly, cardmaster is treating those 3 TI's like LoRa's.

Not sure if it will help or not but here are the 3: 

https://civitai.com/models/97425/danielle-fishel
https://civitai.com/models/88013/rihanna-embedding
https://civitai.com/models/26835/shakira

Right now the only way I can get the other 100 or so TI's to work is to drag and drop the tile into prompt field and then delete all the information it dumps until I have only the trigger word left. Not convenient at all.

**Comment by MxProteus** [comment]
Also just noticed this while reloading my UI in the console window:

Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
*** Error loading script: embedding_editor.py
    Traceback (most recent call last):
      File "D:\Auto1111\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Auto1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Auto1111\stable-diffusion-webui\extensions\stable-diffusion-webui-embedding-editor\scripts\embedding_editor.py", line 2, in <module>
        from webui import wrap_gradio_gpu_call
    ImportError: cannot import name 'wrap_gradio_gpu_call' from 'webui' (D:\Auto1111\stable-diffusion-webui\webui.py)

---------------------------------

Not sure if that's a you problem or a me problem :-). I'm fairly new to Python. Please advise if I need to make changes on my end.

**Comment by GlamoramaAttack** [comment]
Same problem. Textual Inversion no longer working from your extension. And the reason why a new start doesn't help is, that a tiny mistake in your script destroyed the user config.json, that starts with Automatic 1111. That's why I got this message:

> *** Could not load settings
> *** The config file "D:\AI\stable-diffusion-webui\config.json" is likely corrupted
> *** It has been moved to the "tmp/config.json"
> *** Reverting config to default

It quotes  "C:\Python310\lib\json\decoder.py":

>     json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 394 column 1 (char 14462)

At the end of my config.json your script appears, after that the Textual Inversions folder stopped responding: 

```
    "deepbooru_escape": true,
    "deepbooru_filter_tags": "",
    "cardmaster_open_detail_view_on_load": false,
    "cardmaster_card_activation_text_count": "📄➕📑 Number of activation texts and sections",
    "cardmaster_card_activation_hint_primary_color": "#FFFFFF",
    "cardmaster_card_activation_hint_secondary_color": "#f9af3c",
    "cardmaster_click_detail_view_open_single": "📌 Pin card to main detail view",
    "cardmaster_click_detail_view_open_multiple": "📌 Pin card to main detail view",
    "cardmaster_click_detail_view_closed_single": "📎 Apply first activation text",
    "cardmaster_click_detail_view_closed_multiple": "🖇 Apply all activation texts",
    "cardmaster_double_click_detail_view_open_single": "📎 Apply first activation text",
    "cardmaster_double_click_detail_view_open_multiple": "🖇 Apply all activation texts",
    "cardmaster_double_click_detail_view_closed_single": "📎 Apply first activation text",
    "cardmaster_double_click_detail_view_closed_multiple": "🖇 Apply all activation texts",
    "cardmaster_right_click_detail_view_open_single": "🗂 Open compact activation text selector",
    "cardmaster_right_click_detail_view_open_multiple": "🗂 Open compact activation text selector",
    "cardmaster_right_click_detail_view_closed_single": "🖼 Open floating detail view",
    "cardmaster_right_click_detail_view_closed_multiple": "🖼 Open floating detail view"
}
```
As far as I understand (and I hope to understand English better than scripting Java (I'm an amateur) is, the end is missing to be properly enclosed, it should have been like this: 
```

    "cardmaster_right_click_detail_view_closed_multiple": "🖼 Open floating detail view"
 [
        " "
    ]

```

I realized it when I checked my config.json at  https://jsonlint.com/ where you can get that free and without registering. I've spend a whole night with that puzzle. Check your scripts with the part above.

Aside from that I like the idea behind your extension, but I had a little problem with the thumbnail sizes, they always fell back to the smallest size. The way to read the content is perfect though.
